/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import componentes.InfoProduto;
import controladores.ControladorEntidades;
import entidades.Funcionario;
import entidades.Informacoes;
import entidades.Produto;
import entidades.Sessao;
import java.awt.Component;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jsouza
 */
public class TelaBombonier extends javax.swing.JPanel {

    private final Informacoes informacoes;

    public TelaBombonier(Informacoes informacoes) {
        initComponents();
        this.informacoes = informacoes;

        ArrayList<Produto> produtos = new ArrayList<>();
        produtos.add(new Produto("Combo Pipoca Salgada", "1", 10, "resources/combosalgada.jpg", "1 pipoca média salgada, 1 bebida pequena"));
        produtos.add(new Produto("Combo Pipoca Doce", "1", 10, "resources/combomegadoce.jpg", "1 pipoca média doce, 1 bebida pequena"));
        produtos.add(new Produto("Combo Pipoca Fini", "1", 16, "resources/combofini.jpg", "1 pipoca média salgada, 1 bebida média, 1 Fini: 80g"));
        produtos.add(new Produto("Combo Salgado", "2", 14, "resources/combosalgado.jpg", "1 Porção de pão de nuggets, 1 bebida média"));
        produtos.add(new Produto("Combo Balde", "3", 18, "resources/combobalde.jpg", "1 balde de pipoca: salgada ou manteiga, 2 bebidas médias"));
        produtos.add(new Produto("Combo M&MS", "4", 16, "resources/combomms.jpg", "1 pipoca média salgada, 1 bebida média, 1 M&M 49gr (chocolate ou amendoim)"));
        for (Produto produto : produtos) {
            jPanel1.add(new InfoProduto(produto, informacoes));
        }

        if (informacoes.sessao != null) {
            btn_voltar_continuar.setText("Continuar");
        }else{
            btn_voltar_continuar.setText("Voltar");
        }

    }

    public void mensagem() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltar_continuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));

        btn_voltar_continuar.setBackground(new java.awt.Color(52, 163, 55));
        btn_voltar_continuar.setForeground(new java.awt.Color(250, 250, 250));
        btn_voltar_continuar.setText("voltar / continuar");
        btn_voltar_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_continuarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_voltar_continuar)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_voltar_continuar)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("painel");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltar_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_continuarActionPerformed
        if (informacoes.sessao != null) {
            ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPagamento(informacoes);
        } else {
            ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPrincipal();
        }
    }//GEN-LAST:event_btn_voltar_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar_continuar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
