/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import componentes.InfoProduto;
import controladores.ControladorEntidades;
import entidades.Funcionario;
import entidades.Produto;
import entidades.Sessao;
import java.awt.Component;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jsouza
 */
public class TelaBombonier extends javax.swing.JPanel {

    /**
     * Creates new form TelaCompra
     */
    Component frame = null;

    private final Sessao sessao;

    /**
     * Creates new form TelaBombonier
     */
    public TelaBombonier(Sessao sessao) {
        initComponents();
        this.sessao = sessao;

        ArrayList<Produto> produtos = new ArrayList<>();
        produtos.add(new Produto("Pipoca 'n' cream", "1", 10, "resources/pipoca-cream.png"));

        for (Produto produto : produtos) {
            jPanel1.add(new InfoProduto(produto, sessao));
        }

        if (sessao != null) {
            btn_voltar_continuar.setText("Continuar");
        }else{
            btn_voltar_continuar.setText("Voltar");
        }

    }

    public void mensagem() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltar_continuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));

        btn_voltar_continuar.setBackground(new java.awt.Color(52, 163, 55));
        btn_voltar_continuar.setForeground(new java.awt.Color(250, 250, 250));
        btn_voltar_continuar.setText("voltar / continuar");
        btn_voltar_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_continuarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.GridLayout(2, 4, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar_continuar)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_voltar_continuar)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("painel");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltar_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_continuarActionPerformed
        if (sessao != null) {
            ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPagamento(sessao, null);
        } else {
            ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPrincipal();
        }
    }//GEN-LAST:event_btn_voltar_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar_continuar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
