package telas.gerencia;
import entidades.Filme;
import entidades.Sessao;
import entidades.Poltrona;
import entidades.Ingresso;
import controladores.ControladorEntidades;
import entidades.Funcionario;
import entidades.Gerente;
import java.time.Duration;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.*;
import java.util.*;
import telas.MainFrame;
import telas.MainFrame;


/**
 *
 * @author jsouza
 */
public class TelaGerencia extends javax.swing.JPanel {

    /**
     * Creates new form TelaGerencia
     */
   public TelaGerencia(Gerente gerente) {
        initComponents();
        lbl_bem_vindo.setText("Seja bem vindo(a), " + gerente.getNome() + "!");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_listar_filmes = new javax.swing.JButton();
        lbl_bem_vindo = new javax.swing.JLabel();
        btn_adicionar_funcionarios = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        btn_listar_filmes.setBackground(new java.awt.Color(76, 76, 76));
        btn_listar_filmes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_listar_filmes.setForeground(new java.awt.Color(37, 184, 255));
        btn_listar_filmes.setText("Listar Funcionários");
        btn_listar_filmes.setActionCommand("Listar Filmes");
        btn_listar_filmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_filmesActionPerformed(evt);
            }
        });

        lbl_bem_vindo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_bem_vindo.setForeground(new java.awt.Color(37, 184, 255));
        lbl_bem_vindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bem_vindo.setText("label bem vindo");

        btn_adicionar_funcionarios.setBackground(new java.awt.Color(76, 76, 76));
        btn_adicionar_funcionarios.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_adicionar_funcionarios.setForeground(new java.awt.Color(37, 184, 255));
        btn_adicionar_funcionarios.setText("Adicionar Funcionário");
        btn_adicionar_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionar_funcionariosActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 478, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_voltar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_listar_filmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_adicionar_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(390, 390, 390)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_bem_vindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbl_bem_vindo)
                .addGap(30, 30, 30)
                .addComponent(btn_adicionar_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_listar_filmes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(btn_voltar)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionar_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionar_funcionariosActionPerformed
        ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaCadastrarFuncionario();
    }//GEN-LAST:event_btn_adicionar_funcionariosActionPerformed

    private void btn_listar_filmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_filmesActionPerformed
        ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaListarFuncionarios();
    }//GEN-LAST:event_btn_listar_filmesActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPrincipal();
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar_funcionarios;
    private javax.swing.JButton btn_listar_filmes;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lbl_bem_vindo;
    // End of variables declaration//GEN-END:variables
}
